version: "3"

services: 
  selenium:
    container_name: BotLimpieza
    image: selenium/standalone-chrome
    # image: selenium/standalone-chrome:4.1.3-20220427
    # image: selenium/standalone-chrome:4.1.3-20220405
    # image: selenium/standalone-chrome:4.1.3-20220327    
    # image: selenium/standalone-chrome:4.1.2-20220317
    # volumes:
    #   - /dev/shm:/dev/shm
      # - ./app/files:/home/seluser/Downloads
    ports:
      - 4446:4444
      - 0.0.0.0:9222:9222
    restart: always 

  app:
    build: 
      context: .
    volumes:
      - ./app:/app
